In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [ ]:
from google.colab import drive

drive.mount('/content/drive/')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/hw6/Housing.csv')

df

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [ ]:
def h(x, w):
  return x @ w


def gradient_step(X, y, w, learning_rate):
  m = X.shape[1]
  error = h(X, w) - y

  gradient = (X.T @ error) / m

  return w - learning_rate * gradient

def gradient(X, y):
  m, n = X.shape
  w = np.zeros(n)
  learning_rate = 0.0001
  epochs = 100000



  for epoch in range(epochs):
      w = gradient_step(X, y, w, learning_rate)

  return w


features = ['area', 'bedrooms', 'bathrooms', 'price']
scaled_data = StandardScaler().fit_transform(df[features])
scaled_df = pd.DataFrame(scaled_data, columns=features)

X = scaled_df[['area', 'bedrooms', 'bathrooms']]
y = scaled_df['price']
X_b = np.c_[np.ones((X.shape[0],1)), X]

gradient_w = gradient(X_b, y)

gradient_w

array([3.44552165e-16, 4.39452085e-01, 1.60528660e-01, 3.72344423e-01])

In [ ]:
A = X_b.T @ X_b
b = X_b.T @ y
analytics_w = np.linalg.inv(A) @ b

analytics_w

array([7.27580772e-16, 4.39452085e-01, 1.60528660e-01, 3.72344423e-01])

In [ ]:
model = LinearRegression().fit(X, y)

np.insert(model.coef_, 0, model.intercept_)

array([3.16361202e-16, 4.39452085e-01, 1.60528660e-01, 3.72344423e-01])