In [3]:
import numpy as np

result1 = np.arange(1, 11)
result1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
result2 = np.zeros((3, 3))
result2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
result3 = np.random.randint(1, 11, size=(5, 5), dtype=np.int_)
result3

array([[ 8,  8,  2,  2,  8],
       [10, 10,  1,  9,  4],
       [ 5,  1,  5, 10,  3],
       [ 1,  1,  4,  7,  7],
       [ 8, 10,  7,  8,  6]])

In [6]:
res4 = np.random.random(size=(4, 4))
res4

array([[0.439109  , 0.78743136, 0.77026999, 0.68331696],
       [0.15219691, 0.29268858, 0.80957838, 0.23906595],
       [0.55321915, 0.19922446, 0.60745605, 0.54372574],
       [0.55367265, 0.57288192, 0.69698711, 0.60740765]])

In [7]:
arr1 = np.random.randint(1, 11, size=(5))
arr2 = np.random.randint(1, 11, size=(5))
res5_1 = arr1 + arr2
res5_1


array([15,  5,  3,  4, 18])

In [8]:
res5_2 = arr1 - arr2
res5_2

array([-1,  1, -1,  2, -2])

In [9]:
res5_3 = arr1 * arr2
res5_3

array([56,  6,  2,  3, 80])

In [10]:
arr1 = np.random.randint(50, 100, size=(7))
arr2 = np.random.randint(50, 100, size=(7))
res6 = np.dot(arr1, arr2)
res6

np.int64(36646)

In [11]:
arr1 = np.array([[4, 5],
                 [2, 1]])

arr2 = np.array([[6, 2, 7],
                 [3, 0, 5]])

res7 = np.dot(arr1, arr2)
res7

array([[39,  8, 53],
       [15,  4, 19]])

In [12]:
mtrx = np.random.randint(1, 11, size=(3, 3))
res8 = np.linalg.inv(mtrx)
res8

array([[ 1.33333333e-01,  3.75000000e-02, -7.91666667e-02],
       [-2.01451759e-18,  1.87500000e-01, -6.25000000e-02],
       [-6.66666667e-02, -1.75000000e-01,  2.58333333e-01]])

In [13]:
mtrx = np.random.random((4, 4))
res9 = mtrx.T
res9

array([[0.32910335, 0.39416982, 0.33391023, 0.04525812],
       [0.44490996, 0.62968626, 0.44336906, 0.89880524],
       [0.88575623, 0.35041797, 0.11058156, 0.37978232],
       [0.31103278, 0.17243344, 0.13890541, 0.95462255]])

In [14]:
m = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=(1, 4))[0]
res10 = np.dot(m, v)
res10

array([154, 205,  38])

In [15]:
m = np.random.random(size=(2, 3))
v = np.random.random(size=(1, 3))[0]
res11 = np.dot(m, v)
res11


array([0.73858418, 0.93811225])

In [16]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
res12 = m1 * m2
res12

array([[ 14,  60],
       [100,  45]])

In [17]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
res13 = np.dot(m1, m2)
res13

array([[28, 32],
       [31, 32]])

In [18]:
m = np.random.randint(1, 101, size=(5,5 ))
res14 = np.sum(m)
res14

np.int64(1141)

In [19]:
m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))
res15 = m1 - m2
res15

array([[ 3, -1, -1, -1],
       [ 0,  3,  0, -4],
       [ 1,  2,  7, -1],
       [-5, -1,  3,  7]])

In [20]:
m1 = np.random.random(size=(3, 3))
res16 = np.sum(m1, axis=1).reshape(-1, 1)
res16

array([[1.90636567],
       [0.37156795],
       [2.08164767]])

In [21]:
m = np.random.randint(5, 10, size=(3, 4))
res17 = m ** 2
res17

array([[36, 81, 81, 25],
       [81, 49, 36, 25],
       [36, 25, 64, 81]])

In [26]:
v = np.random.randint(1, 50, size=(1, 4))[0]
res18 = np.sqrt(v)
res18

array([5.65685425, 6.8556546 , 6.63324958, 6.63324958])