In [128]:
import numpy as np

# 1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [129]:
# 2
arr = np.arange(1, 7)
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
# 3
a = np.random.randint(1, 11, size=(2, 4))
b = np.random.randint(1, 11, size=(2, 4))

np.vstack((a , b))

array([[ 4,  8,  2,  2],
       [ 8,  8,  1,  3],
       [10, 10,  4,  3],
       [ 6,  9,  2,  1]])

In [131]:
#4
a = np.array([1,2,3])
v = a.reshape(-1, 1)
np.concat((np.hstack((v, v, v)).flatten(), a, a, a))


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [132]:
#5
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

In [133]:
# 6
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.argsort(a)[-5:]

array([18,  7,  3, 10, 15])

In [134]:
# 7
b=np.array([1,2,3,np.nan,5,6,7,np.nan])
b[~np.isnan(b)]

array([1., 2., 3., 5., 6., 7.])

In [146]:
#8
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

np.sqrt(np.sum(((b-a) ** 2)))



np.float64(6.708203932499369)

In [164]:
# 9
find_index = 4
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indeces = np.where(x == 1)[0]

indeces[find_index]

np.int64(8)